import { Student, Book } from "./Report";
export const sampleStudents: Student[] = [
    {
      id: "STU-2023-001",
      name: "John Smith",
      department: "Computer Science",
      year: 2,
      booksCheckedOut: 3,
    },
    {
      id: "STU-2023-002",
      name: "Maria Garcia",
      department: "Engineering",
      year: 3,
      booksCheckedOut: 1,
    },
    {
      id: "STU-2023-003",
      name: "Li Wei",
      department: "Mathematics",
      year: 1,
      booksCheckedOut: 0,
    },
    {
      id: "STU-2023-004",
      name: "Aisha Johnson",
      department: "Biology",
      year: 4,
      booksCheckedOut: 5,
    },
    {
      id: "STU-2023-005",
      name: "David Kim",
      department: "Physics",
      year: 2,
      booksCheckedOut: 2,
    },
    {
      id: "STU-2023-006",
      name: "Sophia Chen",
      department: "Computer Science",
      year: 3,
      booksCheckedOut: 4,
    },
    {
      id: "STU-2023-007",
      name: "James Wilson",
      department: "Psychology",
      year: 1,
      booksCheckedOut: 1,
    },
    {
      id: "STU-2023-008",
      name: "Fatima Ahmed",
      department: "Chemistry",
      year: 4,
      booksCheckedOut: 3,
    },
    {
      id: "STU-2023-009",
      name: "Michael Brown",
      department: "Economics",
      year: 2,
      booksCheckedOut: 0,
    },
    {
      id: "STU-2023-010",
      name: "Emma Davis",
      department: "English Literature",
      year: 3,
      booksCheckedOut: 7,
    },
    {
      id: "STU-2024-011",
      name: "Carlos Rodriguez",
      department: "History",
      year: 1,
      booksCheckedOut: 2,
    },
    {
      id: "STU-2024-012",
      name: "Yuki Tanaka",
      department: "Computer Science",
      year: 2,
      booksCheckedOut: 3,
    },
    {
      id: "STU-2024-013",
      name: "Olivia Martinez",
      department: "Engineering",
      year: 4,
      booksCheckedOut: 6,
    },
    {
      id: "STU-2024-014",
      name: "Ethan Wilson",
      department: "Mathematics",
      year: 1,
      booksCheckedOut: 1,
    },
    {
      id: "STU-2024-015",
      name: "Amina Mohammed",
      department: "Biology",
      year: 3,
      booksCheckedOut: 4,
    }
  ];

  export const sampleBooks: Book[] = [
    {
      id: "BK-001",
      title: "Introduction to Algorithms",
      author: "Thomas H. Cormen",
      isbn: "978-0262033848",
      type: "textbook",
      status: "available",
    },
    {
      id: "BK-002",
      title: "To Kill a Mockingbird",
      author: "Harper Lee",
      isbn: "978-0061120084",
      type: "fiction",
      status: "checked-out",
    },
    {
      id: "BK-003",
      title: "Clean Code: A Handbook",
      author: "Robert C. Martin",
      isbn: "978-0132350884",
      type: "textbook",
      status: "available",
    },
    {
      id: "BK-004",
      title: "The Great Gatsby",
      author: "F. Scott Fitzgerald",
      isbn: "978-0743273565",
      type: "fiction",
      status: "available",
    },
    {
      id: "BK-005",
      title: "Design Patterns: ",
      author: "Erich Gamma, Richard",
      isbn: "978-0201633610",
      type: "textbook",
      status: "checked-out",
    },
    {
      id: "BK-006",
      title: "1984",
      author: "George Orwell",
      isbn: "978-0451524935",
      type: "fiction",
      status: "available",
    },
    {
      id: "BK-007",
      title: "Artificial",
      author: "Stuart Russell, Peter Norvig",
      isbn: "978-0136042594",
      type: "textbook",
      status: "checked-out",
    },
    {
      id: "BK-008",
      title: "The Hobbit",
      author: "J.R.R. Tolkien",
      isbn: "978-0547928227",
      type: "fiction",
      status: "available",
    },
    {
      id: "BK-009",
      title: "Database System Concepts",
      author: "Abraham Silberschatz",
      isbn: "978-0078022159",
      type: "textbook",
      status: "available",
    },
    {
      id: "BK-010",
      title: "Pride and Prejudice",
      author: "Jane Austen",
      isbn: "978-0141439518",
      type: "fiction",
      status: "checked-out",
    },
    {
      id: "BK-011",
      title: "Operating System Concepts",
      author: "Abraham Silberschat",
      isbn: "978-1119800361",
      type: "textbook",
      status: "available",
    },
    {
      id: "BK-012",
      title: "The Lord of the Rings",
      author: "J.R.R. Tolkien",
      isbn: "978-0544003415",
      type: "fiction",
      status: "available",
    },
    {
      id: "BK-013",
      title: "Computer Networks",
      author: "Andrew S.",
      isbn: "978-0132126953",
      type: "textbook",
      status: "checked-out",
    },
    {
      id: "BK-014",
      title: "Brave New World",
      author: "Aldous Huxley",
      isbn: "978-0060850524",
      type: "fiction",
      status: "available",
    },
    {
      id: "BK-015",
      title: "Structure and",
      author: "Harold Abelson,",
      isbn: "978-0262510875",
      type: "textbook",
      status: "available",
    }
  ];
